//state argument is not app state; only the state this reducer is responsible for (the state generated by BooksReducer)
//we set state=null so that if the user hasn't selected a book, the reducer doesn't return 'undefined' which would throw an error.
export default function(state = null, action) {
    switch(action.type) {
        case 'BOOK_SELECTED':
        //don't mutuate state here; always return a fresh object
        return action.payload;
    }
// else, return current state
    return state;

}